#!/bin/sh
#
# Installation script for Rasbian Wheezy. The installation script can be
# run after compiling the binaries. 
#
# Installation:
#
# a) sudo apt-get install sqlite3; sudo apt-get install libsqlite3-dev
#
# b) make
# 
# c) cd doc; ./mktmp102d
# 
# d) sudo ./install (this script)
#
# e) sudo raspi-config (to enable I2C)
#
# f) sudo service tmp102d start
# 
# g) tail -f /var/log/daemon.log
#
# h) sudo update-rc.d tmp102d defaults (optional)
# 
#
# The directories used and files created or modified by this script:
#
# /etc/init.d/tmp102d                - init script
# /etc/tmp102d_config                - configuration file
# /usr/share/man/man1/tmp102d.1      - manual page
# /usr/sbin/insert-tmp102.sh         - database insert script
# /usr/sbin/tmp102d                  - temperature reading daemon
# /var/lib/tmp102d                   - live temperature data
#
# Thu May 29 13:29:01 CEST 2014
# Edit: Sun Feb 22 19:07:45 CET 2015
# 
# Jaakko Koivuniemi
#


# source directory for 'Tmp102d'
SOURCEDIR=${PWD}
SOURCEBIN=${SOURCEDIR}/
SOURCEMAN=${SOURCEDIR}/doc

# binary executables 
BINDIR=/usr/sbin

# manual pages
MANDIR=/usr/share/man/man1

# init script
INITDIR=/etc/init.d

# for tmp102d_conf configuration file
CONFDIR=/etc

# live data 
VARLIBDIR=/var/lib

# binary executables
BINS='tmp102d'

if [ -d $SOURCEBIN ]; then
  echo "Copy binary executables to ${BINDIR}"
  for item in $BINS;
  do
    if [ -r ${SOURCEBIN}/${item} ]; then
       echo "... ${item}"
       /usr/bin/install -C -m 755 ${SOURCEBIN}/${item} ${BINDIR}
    fi 
  done
else
  echo "Source directory ${SOURCEBIN} does not exist"
fi

if [ -d $SOURCEMAN ]; then
  echo "Copy manual pages to ${MANDIR}"
  for item in $BINS;
  do
    if [ -r ${SOURCEMAN}/$item.1 ]; then
       echo "... ${item}.1"
       /usr/bin/install -C -m 664 ${SOURCEMAN}/${item}.1 ${MANDIR}
    fi 
  done
else
  echo "Source directory ${SOURCEMAN} does not exist"
fi

if [ ! -x ${INITDIR}/tmp102d ]; then
  echo "Write init script ${INITDIR}/tmp102d"
  /usr/bin/install -C -m 755 ${SOURCEDIR}/tmp102d.sh ${INITDIR} 
  /bin/mv ${INITDIR}/tmp102d.sh ${INITDIR}/tmp102d
else
  echo "Init script ${INITDIR}/tmp102d already exists"
fi

if [ ! -r ${CONFDIR}/tmp102d_config ]; then
  echo "Write default configuration file ${CONFDIR}/tmp102d_config"
  /usr/bin/install -C -m 664 ${SOURCEDIR}/tmp102d_config ${CONFDIR} 
else
  echo "Configuration file ${CONFDIR}/tmp102d_config already exists" 
fi

if [ -d /var/lib/tmp102d ]; then
  echo "Directory /var/lib/tmp102d already exists"
else
  echo "Create directory /var/lib/tmp102d"
  /bin/mkdir -m 775 /var/lib/tmp102d
fi

echo "Run 'update-rc.d tmp102d defaults' to automatically start at boot time"

