=head1 NAME

tmp102d -  monitor temperature from TMP102 using i2c

=head1 SYNOPSIS

B<tmp102d> 

=head1 DESCRIPTION

The B<tmp102d> is used to read temperature data from TMP102 on Raspberry Pi
using i2c bus. The temperature is written to a file in directory 
/var/lib/tmp102d/ and optionally inserted to local SQLite3 database table.

The daemon is started with command 

B<service> I<tmp102d> I<start>

and can be stopped any time with

B<service> I<tmp102d> I<stop>

The operation of the daemon can be checked from the log file.

=head1 FILES

I</etc/tmp102d_config>             Configuration file. 

I</etc/init.d/tmp102d>             Init script.

I</usr/sbin/tmp102d>               Daemon code.

I</var/lib/tmp102d/temperature>    Live temperature value.

I</var/lib/tmp102d/temperature2>   Second live temperature value.

I</var/lib/tmp102d/temperature3>   Third live temperature value.

I</var/lib/tmp102d/temperature4>   Fourth live temperature value.

I</var/run/tmp102d.pid>            PID file.

=head1 WARNING

No check is done where the query data is written. Could make some hardware 
unusable.

=head1 AUTHORS

Jaakko Koivuniemi 

=head1 SEE ALSO

i2cdetect(8), i2cset(8), i2cget(8), sqlite3(1)

